server:
  port: 8084
spring:
  application:
    name: CLIENT
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 2014
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true