server:
  port: 8082


spring:
  application:
    name: INFO
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 2014
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

email:
  otp:
    expiration-time-seconds: 120

info:
  default:
    photo-id: 295a68bb-790e-4415-b53c-426ee5161da3

jwt:
  custom-secret-key: grgherherherher
