server:
  port: 8085
spring:
  application:
    name: REGISTER
  mail:
    subject: OTP for Zilol Suv
    host: smtp.gmail.com
    port: 587
    username: zilolsuvservice@gmail.com
    password: jpianrjmchmadzmg
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

email:
  otp:
    expiration-time-seconds: 1200

jwt:
  custom-secret-key: grgherherherher
