package product.enums;

public enum ApiStatus {
    WRONG_EMAIL,
    EMAIL_ALREADY_USED,
    BAD_PASSWORD,
    WRONG_TOKEN,
    TOKEN_EXPIRED,
    WRONG_CODE,
    CLIENT_NOT_FOUND, INFO_NOT_FOUND, NOT_ACCESS, SELLER_NOT_FOUND, PHOTO_NOT_FOUND, WRONG_PRODUCT_TYPE, PRODUCT_NOT_FOUND, DESCRIPTION_LARGE, SERVER_ERROR
}
