code-template: templates/send-code.vm


spring:
  mail:
    subject: OTP for Zilol Suv
    host: smtp.gmail.com
    port: 587
    username: zilolsuvservice@gmail.com
    password: jpianrjmchmadzmg
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
