server:
  port: 8085
spring:
  application:
    name: REGISTER


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

email:
  otp:
    expiration-time-seconds: 1200

jwt:
  custom-secret-key: grgherherherher
